version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.release
    container_name: express-boillerplate
    ports: 
      - 2000:2000
    env_file: 
      - .env
    networks:
      - gateway 
    restart: always
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-southeast-1"

networks:
  gateway:
    external:
      name: boillerplate-network