version: '3'
services:

  mongodb_service:
    image: mongo:4.2
    container_name: mongodb_service
    networks:
      express_boillerplate_network:
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  # Nodejs
  boillerplate:
    container_name: boillerplate
    build:
      context: .
      dockerfile: Dockerfile.release
    networks:
      express_boillerplate_network:
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongodb_service

#Docker Networks
networks:
  express_boillerplate_network:
    driver: bridge

#Volumes
volumes:
  mongodb_service:
    driver: local
  mongodb_service_config:
    driver: local
