# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Build the stack
    - uses: actions/checkout@v2
    - env:
       APP_PORT: ${{ Boilerplate-env.APP_PORT }}
       MONGO_INITDB_DATABASE: ${{ Boilerplate-env.MONGO_INITDB_DATABASE }}
       MONGO_INITDB_ROOT_PASSWORD: ${{ Boilerplate-env.MONGO_INITDB_ROOT_PASSWORD }}
       MONGO_INITDB_ROOT_USERNAME: ${{ Boilerplate-env.MONGO_INITDB_ROOT_USERNAME }}
       MONGO_PORT: ${{ Boilerplate-env.MONGO_PORT }}
      run: docker-compose up --build
      
    - name: Use Node.js ${{ matrix.node-version }} && install dependencies
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install

    - name: coverage
      uses: codecov/codecov-action@v1
      with:
        name: actions ${{ matrix.node }}
        fail_ci_if_error: false
